# Default initial positions for ur10e's ros2_control fake system

initial_positions:
  robot1_elbow_joint: 0
  robot1_shoulder_lift_joint: 0
  robot1_shoulder_pan_joint: 0
  robot1_wrist_1_joint: 0
  robot1_wrist_2_joint: 0
  robot1_wrist_3_joint: 0